### ISSUE TITLE
Crash suite mise à jour - 'module 'hashlib' has no attribute 'blake2s'

### ISSUE THREAD

**Issue by Guintolli** [guillaumezin/DomoticzLinky#147]
Bonjour,

Fervent utilisateur depuis un certain temps du plugin, j'ai du faire la mise à jour (v2.4.0) comme le plugin le demandait.
Depuis cette la mise à jour, le plugin part en erreur et fait planter Domoticz. Je suis obligé de redémarrer le service domoticz (et de désactiver le plugin sinon rebelote).

L'erreur remontée dans les logs par le plugin est la suivante:
```
2021-07-04 11:43:34.238  Error: (Linky) 'onMessage' failed 'AttributeError':'module 'hashlib' has no attribute 'blake2s''.
2021-07-04 11:43:34.241  Error: Domoticz(pid:13113, tid:13119('PluginMgr')) received fatal signal 11 (Segmentation fault)
2021-07-04 11:43:34.244  Error: siginfo address=0x3339, address=(nil)
2021-07-04 11:43:36.894  Error: Thread 4 (Thread 0x74c41430 (LWP 13119)):
2021-07-04 11:43:36.894  Error: #0  __waitpid (options=0, stat_loc=0x74c3fec8, pid=13394) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2021-07-04 11:43:36.894  Error: #1  __waitpid (pid=13394, stat_loc=0x74c3fec8, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2021-07-04 11:43:36.894  Error: #2  0x002db8ec in dumpstack_gdb(bool) ()
2021-07-04 11:43:36.894  Error: #3  0x002dbeb8 in signal_handler(int, siginfo_t*, void*) ()
2021-07-04 11:43:36.894  Error: #4  <signal handler called>
2021-07-04 11:43:36.894  Error: #5  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
2021-07-04 11:43:36.894  Error: #6  <signal handler called>
2021-07-04 11:43:36.894  Error: #7  0x75ccdee0 in _PyUnicode_AsASCIIString () from /usr/lib/arm-linux-gnueabihf/libpython3.5m.so
2021-07-04 11:43:36.895  Error: #8  0x0061a334 in Plugins::CPlugin::LogPythonException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
2021-07-04 11:43:36.895  Error: #9  0x0061ac84 in Plugins::CPlugin::Callback(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*) ()
2021-07-04 11:43:36.895  Error: #10 0x00264080 in Plugins::CCallbackBase::Callback(_object*) ()
2021-07-04 11:43:36.895  Error: #11 0x00635f64 in Plugins::onMessageCallback::ProcessLocked() ()
2021-07-04 11:43:36.895  Error: #12 0x00264218 in Plugins::CPluginMessageBase::Process() ()
2021-07-04 11:43:36.895  Error: #13 0x00626d08 in Plugins::CPluginSystem::Do_Work() ()
2021-07-04 11:43:36.895  Error: #14 0x009447ec in execute_native_thread_routine ()
2021-07-04 11:43:36.895  Error: #15 0x76c9a494 in start_thread (arg=0x74c41430) at pthread_create.c:486
2021-07-04 11:43:36.895  Error: #16 0x76b4d578 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
```

Ma solution domoticz tourne sur un Raspberry Pi 3 avec pour OS: Linux raspberrypi 4.14.98-v7+
Ma version de domoticz est: 2020.2 (je n'ai pas fait la dernière mise à jour car la précédente était déjà galère avec la nécessité de mise à jour de librairies etc...)

Auriez-vous une idée de comment résoudre ce soucis (si possible en évitant la mise à jour de Domoticz)?

Je vous remercie par avance.

**Comment by guillaumezin** [comment]
Bonjour,
Depuis peu de temps, j'utilise la fonction blake2s et vous avez raison, il faut au moins python 3.6 pour cela, et vous avez la version 3.5. Je vais voir si je peux trouver un contournement sur la prochaine version, laissez moi quelques jours.

**Comment by Guintolli** [comment]
Merci :)

**Comment by guillaumezin** [comment]
Bonsoir, pouvez-vous essayer la version 2.4.1 ?

**Comment by Guintolli** [comment]
Bonsoir,
Je viens de mettre à jour et tester.
Je ne rencontre plus d'erreur. Les données sont bien récupérées et les différentes vues mise à jour.
Merci!
