### ISSUE TITLE
crash domoticz - lors d'un "modifier" sur une ligne domoticzlinky

### ISSUE THREAD

**Issue by Phil353556** [guillaumezin/DomoticzLinky#180]
Bonjour,
Tout fonctionnait depuis 1 an. Merci !
Ne pas oublier les dates anniversaires ...  :
- Enedis : collecte horaire à revalider tous les ans 
- Collecte russandol : tous les trois ans.
Ce n'est pas la première fois que je remarque qu'une modification de la ligne linky par exemple pour changer le nombre de jour de collecte ou faire un "reset consentement" a pour conséquence, après appui sur "modifier" un crash de domoticz 

2022-07-21 11:37:41.280  Error: (FindModule) Domoticz/DomoticzEx modules not found in interpreter.
2022-07-21 11:37:41.280  Error: (FindModule) Domoticz/DomoticzEx modules not found in interpreter.
2022-07-21 11:37:41.307  Error: Domoticz(pid:32008, tid:32055('Compteur xxxxx')) received fatal signal 11 (Segmentation fault)
2022-07-21 11:37:41.307  Error: siginfo address=0x7d08, address=(nil)
2022-07-21 11:37:41.353  Status: Compteur xxxxx Stopping threads.
2022-07-21 11:37:44.108  Error: Thread 17 (Thread 0xac7fd200 (LWP 32055)):
2022-07-21 11:37:44.109  Error: #0  __waitpid (options=0, stat_loc=0xac7fbf98, pid=4723) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2022-07-21 11:37:44.109  Error: #1  __waitpid (pid=4723, stat_loc=0xac7fbf98, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2022-07-21 11:37:44.109  Error: #2  0x0029121c in dumpstack_gdb(bool) ()
2022-07-21 11:37:44.109  Error: #3  0x002917e8 in signal_handler(int, siginfo_t*, void*) ()
2022-07-21 11:37:44.109  Error: #4  <signal handler called>
2022-07-21 11:37:44.109  Error: #5  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
2022-07-21 11:37:44.109  Error: #6  <signal handler called>
2022-07-21 11:37:44.109  Error: #7  0xb5c8f724 in ?? () from /usr/lib/arm-linux-gnueabihf/libpython3.7m.so
2022-07-21 11:37:44.109  Error: #8  0xb5c8f714 in ?? () from /usr/lib/arm-linux-gnueabihf/libpython3.7m.so

Redémarrage de domoticz et c'est bon. 
2022-07-21 11:38:05.857  Status: Domoticz V2022.1 (c)2012-2022 GizMoCuz

Version de domoticz :  V2022.1
Raspberry pi : Raspberry Pi 4 Model B Rev 1.2
OS : Raspbian GNU/Linux 10 (buster)
Kernel: 5.15.28-v7l+
Memory : 4Go ( neofecth indique : Memory: 402MiB / 3755MiB) 

Merci -  bonnes vacances à vous - à regarder après :-)

**Comment by Phil353556** [comment]
Merci @guillaumezin 
Je clos le ticket
