### ISSUE TITLE
plus de données?

### ISSUE THREAD

**Issue by dltrainou** [guillaumezin/DomoticzLinky#190]

**Comment by dltrainou** [comment]
Bonjour a tous et bonne et heureuse année 2023
Sans rien changer, plus de données depuis le 29/12?
Sur le site Enedis en journalier c'est OK, mais en horaire, pas de données depuis le 29!!
suis je le seul? merci et bonne journée

**Comment by AlphaXMines** [comment]
Bonjour,
j'ai le meme problème depuis la même date. 

Quelques éléments: j'utilise domoticz 2022.2 (release) sur un raspberry. Dans les logs, le plugin indique l'erreur suivante:
 2023-01-02 09:53:51.724 Status: Linky: Durant l'étape getdatahours de 2022-12-26 à 2023-01-02 - Pas de données disponibles, ni en consommation, ni en production, avez-vous associé un compteur à votre compte et demandé l'enregistrement et la collecte des données horaire sur le site d'Enedis (dans "Gérer l'accès à mes données") ?

``
2023-01-02 09:53:53.887 Status: Linky: Durant l'étape save de 2023-01-01 à 2023-01-02 - Données manquantes pour mettre à jour le tableau de bord
2023-01-02 09:53:53.887 Error: Linky: Call to function 'onMessage' failed, exception details:
2023-01-02 09:53:53.923 Error: Linky: Traceback (most recent call last):
2023-01-02 09:53:53.923 Error: Linky: File "/misc/domoticz/plugins/DomoticzLinky/plugin.py", line 2269, in onMessage
2023-01-02 09:53:53.923 Error: Linky: _plugin.onMessage(Connection, Data)
2023-01-02 09:53:53.923 Error: Linky: File "/misc/domoticz/plugins/DomoticzLinky/plugin.py", line 2090, in onMessage
2023-01-02 09:53:53.923 Error: Linky: self.handleConnection(Data)
2023-01-02 09:53:53.923 Error: Linky: File "/misc/domoticz/plugins/DomoticzLinky/plugin.py", line 1872, in handleConnection
2023-01-02 09:53:53.924 Error: Linky: self.handleConnection(bUseCache = bUseCache, bNoDataInCache = bNoDataInCache)
2023-01-02 09:53:53.924 Error: Linky: File "/misc/domoticz/plugins/DomoticzLinky/plugin.py", line 1847, in handleConnection
2023-01-02 09:53:53.924 Error: Linky: if not self.mergeCounters():
2023-01-02 09:53:53.924 Error: Linky: File "/misc/domoticz/plugins/DomoticzLinky/plugin.py", line 992, in mergeCounters
2023-01-02 09:53:53.924 Error: Linky: not dCalculateCopy[sUsagePointConsumptionId]["production1"]["value_year"]
2023-01-02 09:53:53.924 Error: Linky: KeyError: 'value_year' 
``

**Comment by MacAre** [comment]
Bonjour,
Idem pour moi. Dernière info reçue le 29/12/2022.

Domoticz 2022.2 (build 14901)
OS (uname -a): 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux
Matériel: Raspberry PI3

Bonne année à tous :-)

**Comment by Phil353556** [comment]
Bonjour,
Idem pour moi.
- Raspberry Pi 4 Model B Rev 1.2 / 4Go
- Domoticz V2022.2 (c)2012-2022 GizMoCuz
   2022-12-29 17:07:43.318  Status: Build Hash: eea9db734, Date: 2022-11-05 13:05:35
   
```
   2023-01-02 08:54:45.115  Status: Compteur xxxxx: Récupération des données avec l'historique court
2023-01-02 08:54:45.149  Status: Compteur xxxxx: Traitement pour le point de livraison xxxxx
2023-01-02 08:54:56.663  Status: Compteur xxxxx: Durant l'étape getdatahours de 2022-12-26 à 2023-01-02 - Pas de données disponibles, ni en consommation, ni en production, avez-vous associé un compteur à votre compte et demandé l'enregistrement et la collecte des données horaire sur le site d'Enedis (dans "Gérer l'accès à mes données") ?
2023-01-02 08:54:58.270  Status: Compteur xxxxx: Durant l'étape save de 2022-12-26 à 2023-01-02 - Données manquantes pour mettre à jour le tableau de bord
2023-01-02 08:54:58.270  Error: Compteur xxxxx: Call to function 'onMessage' failed, exception details:
2023-01-02 08:54:58.274  Error: Compteur xxxxx: Traceback (most recent call last):
2023-01-02 08:54:58.274  Error: Compteur xxxxx:   File "/home/domoticz/hdd.domoticz/plugins/DomoticzLinky/plugin.py", line 2254, in onMessage
2023-01-02 08:54:58.274  Error: Compteur xxxxx:     _plugin.onMessage(Connection, Data)
2023-01-02 08:54:58.274  Error: Compteur xxxxx:   File "/home/domoticz/hdd.domoticz/plugins/DomoticzLinky/plugin.py", line 2090, in onMessage
2023-01-02 08:54:58.275  Error: Compteur xxxxx:     self.handleConnection(Data)
2023-01-02 08:54:58.275  Error: Compteur xxxxx:   File "/home/domoticz/hdd.domoticz/plugins/DomoticzLinky/plugin.py", line 1872, in handleConnection
2023-01-02 08:54:58.275  Error: Compteur xxxxx:     self.handleConnection(bUseCache = bUseCache, bNoDataInCache = bNoDataInCache)
2023-01-02 08:54:58.275  Error: Compteur xxxxx:   File "/home/domoticz/hdd.domoticz/plugins/DomoticzLinky/plugin.py", line 1847, in handleConnection
2023-01-02 08:54:58.275  Error: Compteur xxxxx:     if not self.mergeCounters():
2023-01-02 08:54:58.275  Error: Compteur xxxxx:   File "/home/domoticz/hdd.domoticz/plugins/DomoticzLinky/plugin.py", line 992, in mergeCounters
2023-01-02 08:54:58.275  Error: Compteur xxxxx:     not dCalculateCopy[sUsagePointConsumptionId]["production1"]["value_year"]
2023-01-02 08:54:58.275  Error: Compteur xxxxx: KeyError: 'value_year'
```
Excellente année à tous,  santé d'abord
 -

**Comment by anthog21** [comment]
Bonjour,

pareil chez moi, et sur le site d'Enedis il n'y a rien non plus pour le 30 et 31/12, le problème doit venir de chez eux.

A+

**Comment by Phil353556** [comment]
exact, on va attendre que cela revienne
![image](https://user-images.githubusercontent.com/64729485/210221451-ed844a49-c6e9-44ae-8f9d-ecdd80016698.png)

**Comment by guillaumezin** [comment]
Bonjour, et bonne année. J'ai vu, c'est pareil chez moi, j'investigue, mais laissez-moi quelques jours. Et je viens de voir que l'interface d'accès va changer au 1er mai, donc il y aura de toute façon une nouvelle version du plugin entre temps.

**Comment by dltrainou** [comment]
Bonjour., c'est reparti ce matin, sans aucune explication d'Enedis sur son site!!!!
Bonne journée

**Comment by Phil353556** [comment]
- Effectivement, c'est revenu

**Comment by guillaumezin** [comment]
Je clos, pour que ça revienne, éventuellement allez dans les paramètres du plugin et cliquez juste sur "Modifier" pour relancer la synchronisation.
