### ISSUE TITLE
Erreur au 1er janvier 2023

### ISSUE THREAD

**Issue by Madcat-76310** [guillaumezin/DomoticzLinky#191]
Bonjour et Bonne Année !

Il semblerait que le plugin se soit arrêté au 1er janvier, avec plusieurs erreurs :

2023-01-06 08:11:29.237 Error: Linky: Call to function 'onHeartbeat' failed, exception details:
2023-01-06 08:11:29.241 Error: Linky: Traceback (most recent call last):
2023-01-06 08:11:29.241 Error: Linky: File "/home/freebox/domoticz/plugins/DomoticzLinky/plugin.py", line 2301, in onHeartbeat
2023-01-06 08:11:29.241 Error: Linky: _plugin.onHeartbeat()
2023-01-06 08:11:29.241 Error: Linky: File "/home/freebox/domoticz/plugins/DomoticzLinky/plugin.py", line 2129, in onHeartbeat
2023-01-06 08:11:29.241 Error: Linky: self.handleConnection()
2023-01-06 08:11:29.241 Error: Linky: File "/home/freebox/domoticz/plugins/DomoticzLinky/plugin.py", line 1847, in handleConnection
2023-01-06 08:11:29.241 Error: Linky: if not self.mergeCounters():
2023-01-06 08:11:29.241 Error: Linky: File "/home/freebox/domoticz/plugins/DomoticzLinky/plugin.py", line 992, in mergeCounters
2023-01-06 08:11:29.241 Error: Linky: not dCalculateCopy[sUsagePointConsumptionId]["production1"]["value_year"]
2023-01-06 08:11:29.241 Error: Linky: KeyError: 'value_year'

Ce n'est peut-être pas grand chose, mais il n'y a plus de remontée du Linky.
Merci !

**Comment by Guintolli** [comment]
Bonjour,

Je constate également la même erreur:

` 2023-01-06 08:07:28.496 Error: Linky: Call to function 'onHeartbeat' failed, exception details:
2023-01-06 08:07:28.498 Error: Linky: Traceback (most recent call last):
2023-01-06 08:07:28.498 Error: Linky: File "/home/pi/domoticz/plugins/DomoticzLinky/plugin.py", line 2301, in onHeartbeat
2023-01-06 08:07:28.498 Error: Linky: _plugin.onHeartbeat()
2023-01-06 08:07:28.498 Error: Linky: File "/home/pi/domoticz/plugins/DomoticzLinky/plugin.py", line 2129, in onHeartbeat
2023-01-06 08:07:28.498 Error: Linky: self.handleConnection()
2023-01-06 08:07:28.498 Error: Linky: File "/home/pi/domoticz/plugins/DomoticzLinky/plugin.py", line 1847, in handleConnection
2023-01-06 08:07:28.498 Error: Linky: if not self.mergeCounters():
2023-01-06 08:07:28.498 Error: Linky: File "/home/pi/domoticz/plugins/DomoticzLinky/plugin.py", line 992, in mergeCounters
2023-01-06 08:07:28.498 Error: Linky: not dCalculateCopy[sUsagePointConsumptionId]["production1"]["value_year"]
2023-01-06 08:07:28.498 Error: Linky: KeyError: 'value_year' `

Merci d'avance

**Comment by dranreb38** [comment]
Bonjour, 
Idem chez moi

**Comment by Madcat-76310** [comment]
Effectivement, après un rebooté, cela refonctionne. Tant mieux, merci, et meilleurs voeux !

**Comment by Guintolli** [comment]
En voyant vos retours, j'ai redémarré le service domoticz et magie ça refonctionne.
Merci
